### ISSUE TITLE
Make encryption for field differences optional

### ISSUE THREAD

**Issue by MartinKanters** [rabobank/shadow-tool#58]
**Is your feature request related to a problem? Please describe.**
I understand that backends might contain sensitive information, so that you/we made the encryption mandatory, but in some cases it's not the case.

**Describe the solution you'd like**
Make the encryption optional in the builder, but have it activated by default.

**Comment by martinvisser** [comment]
@MartinKanters so invert the current set-up?

**Comment by MartinKanters** [comment]
I would say let's keep the encryption enabled by default, and allow people to turn it off.

**Comment by martinvisser** [comment]
Indeed, you could add like a `NoopEncryptionService` or something like that after that PR is merged. @MartinKanters agree?

**Comment by MartinKanters** [comment]
I agree, that would be a nice solution. It ensures that people will not accidentally log sensitive data, but still opens up logging the data without encryption.
Perhaps we can add a line to the documentation about this possibility? (Maybe more docs need to be written to cover #72 anyway?)
